name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up caching for Buildozer global directory
      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: ~/.buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      # Step 3: Cache project-specific dependencies
      - name: Cache Buildozer local directory
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-

      # Step 4: Pull and run Buildozer
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          docker_image: kivy/buildozer:stable
          command: buildozer android debug

      # Step 5: Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: ${{ steps.buildozer.outputs.filename }}
